## Working with Missing Data in Pandas

In [ ]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [22]:
data = {'names':['steve','john','richard','sarah','randy','micheal','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender':['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1]= np.nan
ranking_df.iloc[3:6,3]= np.nan
ranking_df.iloc[3,:]= np.nan
ranking_df

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [ ]:
ranking_df.isnull()

In [ ]:
ranking_df.notnull()

In [ ]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

In [ ]:
ranking_df.fillna(0)

In [ ]:
ranking_df.ffill()

In [ ]:
ranking_df.bfill()

In [ ]:
ranking_df.interpolate(method='linear')

In [23]:
ranking_df.dropna()

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0

In [24]:
ranking_df.dropna(how='all')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [25]:
ranking_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [26]:
ranking_df.dropna(axis=0)

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0